### ISSUE TITLE
Command old

### ISSUE THREAD

**Issue by hugolm20** [danilo-nzyte/airbyte-terraform-gcp#1]
Hi, danilo! 

I think the commands bellow [airbyte-terraform-gcp](https://github.com/danilo-nzyte/airbyte-terraform-gcp)/[sh_scripts](https://github.com/danilo-nzyte/airbyte-terraform-gcp/tree/main/sh_scripts)/airbyte.sh are old:

```
curl -sOO https://raw.githubusercontent.com/airbytehq/airbyte/master/.env
curl -sOO https://raw.githubusercontent.com/airbytehq/airbyte/master/docker-compose.yaml
curl -sOO https://raw.githubusercontent.com/airbytehq/airbyte/master/flags.yml
```

I tried to run them in my terminal and didn't worth. 
After look for and found in airbyte's site , i think the new command is:

`curl -sOO https://raw.githubusercontent.com/airbytehq/airbyte-platform/main/{.env,flags.yml,docker-compose.yaml}`

**Comment by danilo-nzyte** [comment]
Hi @Hugolm20

Thanks for this. I haven't looked at this repo since the first commit, but I've made the change as per your suggestion.

Seems that they've restructured their repo to rename the master branch and changed the name of the folder at the same time.

Thanks again :)
